refactor: Refactor codebase for further dev (library) (#3)
* Make yolov9 as a library for further dev

* Limit numpy < 2 and setuptools < 81

* Add .gitignore

* Fix AttributeError: 'FreeTypeFont' object has no attribute 'getsize' by using newer API (WongKinYiu/yolov9#33) & Limit Pillow version >= 10

* Fix import method by using absolute path instead of relative while loading weights

* Move data folder to yolov9 and Link to orginal location for compatibility

* Refactor the accessing method to ROOT varible and Remove unnecessary sys.path addition in yolov9 lib

* Move logger tools to tools folder

* Support uploading dataset from an absolute path in CometLogger

* Fix the way to get requirements.txt in checking requirements

* Move export_* functions to yolov9 lib to avoid the yolov9 lib depending on export.py

* Fix relative import in yolov9.utils.general

* Fix incorrect import in tools/wandb/log_dataset.py

* Ignore runs folder

* Remove useless imports in all task scripts && Make data, cfg, runs folder relative to WORKDIR_ROOT and dataset path relative to DATASETS_DIR

* Change to use RANK, LOCAL_RANK, WORLD_SIZE variable from yolov9.utils.general

* Limit albumentations < 2 to avoid API changes

* Ignore wandb folder

* refactor: Remove duplicate codes for detection (#1)

* Combine val.py, val_dual.py, val_triple.py with a switch, model-type

* Move ModelType enum to yolov9.utils

* Combine train.py, train_*.py with a switch, model-type

* Only handle train_out if compute_loss is True in val.py

* Combine detect.py, detect_dual.py with a switch, model-type

* Use argparse.ArgumentDefaultsHelpFormatter as formatter_class in val.py

* Add a setup_distributed() function for consistent setup in different tasks (#2)

* fix: Remove unnecessary login function call in wandb to work in offline mode

* feat: Move enums to a file and Support exporting to YAML

* fix: Use the model type in arguments for backward compatibility if resuming from old experiments

* fix: Support resuming from new experiments

* feat: Support calculating losses in validation stage

* fix: Make output format of TripleDDetect compatible with other versions